sudo: false

language: node_js

node_js:
  - '8'

cache:
  directories:
  - node_modules

before_install:
- npm update
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0

install:
- npm install
script:

- npm test
- npx jest --coverage